<template>
  <div class="modal modal-open">
    <div class="modal-box max-w-2xl">
      <div class="flex justify-between items-center mb-4">
        <h3 class="text-lg font-bold">Two-Factor Authentication Settings</h3>
        <button @click="close" class="btn btn-sm btn-circle btn-ghost">✕</button>
      </div>

      <!-- 2FA Status -->
      <div class="bg-base-200 p-4 rounded-lg mb-6">
        <div class="flex items-center justify-between">
          <div>
            <h4 class="font-medium">Two-Factor Authentication</h4>
            <p class="text-sm">
              {{ is2FAEnabled ? '2FA is currently enabled for your account' : '2FA is currently disabled' }}
            </p>
          </div>
          <button
            @click="toggle2FA"
            class="btn btn-sm"
            :class="is2FAEnabled ? 'btn-error' : 'btn-primary'"
          >
            {{ is2FAEnabled ? 'Disable' : 'Enable' }} 2FA
          </button>
        </div>
      </div>

      <!-- 2FA Setup (shown when enabling) -->
      <div v-if="showSetup" class="mb-6">
        <div class="text-center mb-4">
          <div class="inline-block p-4 bg-white rounded-lg">
            <!-- QR Code would be generated by backend in a real app -->
            <div class="w-48 h-48 bg-gray-100 flex items-center justify-center">
              <span class="text-gray-500">QR Code would appear here</span>
            </div>
          </div>
        </div>

        <div class="mb-4">
          <p class="text-sm mb-2">Or enter this code manually:</p>
          <div class="bg-base-200 p-3 rounded-lg text-center font-mono">
            JBSWY3DPEHPK3PXP
          </div>
        </div>

        <div class="form-control">
          <label class="label">
            <span class="label-text">Verification Code</span>
          </label>
          <input
            v-model="verificationCode"
            type="text"
            placeholder="Enter 6-digit code"
            class="input input-bordered w-full"
          />
          <button @click="verify2FA" class="btn btn-primary mt-2">
            Verify & Enable 2FA
          </button>
        </div>
      </div>

      <!-- Backup Codes -->
      <div v-if="is2FAEnabled" class="bg-base-200 p-4 rounded-lg">
        <h4 class="font-medium mb-2">Backup Codes</h4>
        <p class="text-sm mb-3">
          Save these backup codes in a secure place. You can use them to access your account if you lose access to your authenticator app.
        </p>

        <div class="grid grid-cols-2 gap-2 mb-4">
          <div
            v-for="(code, index) in backupCodes"
            :key="index"
            class="bg-white p-2 rounded text-center font-mono"
          >
            {{ code }}
          </div>
        </div>

        <div class="flex gap-2">
          <button @click="generateNewBackupCodes" class="btn btn-sm btn-outline">
            Generate New Codes
          </button>
          <button @click="downloadBackupCodes" class="btn btn-sm btn-outline">
            Download Codes
          </button>
        </div>
      </div>

      <div class="modal-action">
        <button @click="close" class="btn">Close</button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'


const emit = defineEmits(['close'])

const is2FAEnabled = ref(false)
const showSetup = ref(false)
const verificationCode = ref('')

const backupCodes = ref([
  '3K7Q-9P2R-4T6Y',
  '8W1U-5O9I-2L4K',
  '7J3H-6G5F-1D2S',
  '9A8Z-4X7C-0V3B',
  '5N6M-2Q1W-8E4R'
])

const close = () => {
  emit('close')
}

const toggle2FA = () => {
  if (is2FAEnabled.value) {
    is2FAEnabled.value = false
    showSetup.value = false
  } else {
    showSetup.value = true
  }
}

const verify2FA = () => {
  // In a real app, you would verify the code with your backend
  if (verificationCode.value.length === 6) {
    is2FAEnabled.value = true
    showSetup.value = false
  } else {
    console.log('Invalid verification code')
  }
}

const generateNewBackupCodes = () => {
  // In a real app, this would call your backend
  backupCodes.value = Array(5).fill().map(() => {
    return `${randomString(3)}-${randomString(3)}-${randomString(3)}`.toUpperCase()
  })
}

const downloadBackupCodes = () => {
  // In a real app, this would create a downloadable file
}

const randomString = (length) => {
  const chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  let result = ''
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return result
}
</script>
